"use strict";
const $=id=>document.getElementById(id),canvas=$("gl"),overlay=$("overlay"),ctx=overlay.getContext("2d"),Nav=window.CropNavigation,Poly=window.CropPolygon;
let gl,program,posBuffer,colorBuffer,flagBuffer,xyz,positions,localCoordinates,colors,flags,meta,cropFrame;
let polygon=[],hoverInsert=null,pointMode="all",view="top",orbitCamera=null,freeOrbitBasis=null,inspectCameraInitialized=false,inspectZoom=.9,verticalLock=true,zoom=.9,pan=[0,0],orbitTarget=[0,0,0],dragging=false,dragVertex=-1,dragAction="",last=[0,0];
let localCenter=[0,0,0],localHalf=1,localBounds,selectedPreview=0;
const vertexSource=`attribute vec3 p;attribute vec3 c;attribute float f;uniform vec3 pivot;uniform vec3 viewRight;uniform vec3 viewUp;uniform vec3 viewDepth;uniform vec2 fit;uniform float zoom;uniform vec2 pan;uniform int mode;varying vec3 color;void main(){vec3 d=p-pivot;vec3 q=vec3(dot(d,viewRight),dot(d,viewUp),dot(d,viewDepth));bool hide=(mode==1&&f<.5)||(mode==2&&f>.5);gl_Position=hide?vec4(2.,2.,2.,1.):vec4(q.x*zoom*fit.x+pan.x,q.y*zoom*fit.y+pan.y,q.z*.01,1.);gl_PointSize=1.5;color=f>.5?mix(c,vec3(1.,.72,.08),.62):c;}`;
const fragmentSource=`precision mediump float;varying vec3 color;void main(){gl_FragColor=vec4(color,1.);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function initGL(){gl=canvas.getContext("webgl",{antialias:false});if(!gl)throw Error("WebGL is unavailable");program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertexSource));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragmentSource));gl.linkProgram(program);gl.useProgram(program);posBuffer=gl.createBuffer();colorBuffer=gl.createBuffer();flagBuffer=gl.createBuffer();gl.clearColor(.035,.055,.068,1)}
function upload(buffer,data,usage=gl.STATIC_DRAW){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,usage)}
function attribute(name,buffer,size){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const location=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,size,gl.FLOAT,false,0,0)}
function fitScale(){const aspect=canvas.clientWidth/canvas.clientHeight;return aspect>1?[1/aspect,1]:[1,aspect]}
function resize(){const d=devicePixelRatio||1;for(const c of[canvas,overlay]){c.width=c.clientWidth*d;c.height=c.clientHeight*d}gl.viewport(0,0,canvas.width,canvas.height);draw()}
function viewBasis(){if(Nav.FIXED_BASES[view])return Nav.FIXED_BASES[view];return verticalLock?Nav.topTiltBasis(orbitCamera):freeOrbitBasis}
function updateOrbitDebug(){let camera="";if(orbitCamera){if(verticalLock){const magnitude=Math.hypot(orbitCamera.tiltX,orbitCamera.tiltY);camera=`tilt X ${(orbitCamera.tiltX*180/Math.PI).toFixed(1)}°\ntilt Y ${(orbitCamera.tiltY*180/Math.PI).toFixed(1)}°\ntilt magnitude ${(magnitude*180/Math.PI).toFixed(1)}°\n`}else camera="free orbit\n";camera+=`distance ${orbitCamera.distance.toFixed(3)}\n`}$('orbitDebug').textContent=`${camera}pivot [${orbitTarget.map(value=>value.toFixed(4)).join(", ")}]\nvertical lock: ${verticalLock?"ON":"OFF"}`}
function draw(){if(!positions)return;gl.clear(gl.COLOR_BUFFER_BIT);attribute("p",posBuffer,3);attribute("c",colorBuffer,3);attribute("f",flagBuffer,1);const pivot=view==="inspect"?orbitTarget:[0,0,0],basis=viewBasis();gl.uniform3f(gl.getUniformLocation(program,"pivot"),pivot[0],pivot[1],pivot[2]);gl.uniform3fv(gl.getUniformLocation(program,"viewRight"),basis.right);gl.uniform3fv(gl.getUniformLocation(program,"viewUp"),basis.up);gl.uniform3fv(gl.getUniformLocation(program,"viewDepth"),basis.depth);const f=fitScale();gl.uniform2f(gl.getUniformLocation(program,"fit"),f[0],f[1]);gl.uniform1f(gl.getUniformLocation(program,"zoom"),zoom);gl.uniform2f(gl.getUniformLocation(program,"pan"),pan[0],pan[1]);gl.uniform1i(gl.getUniformLocation(program,"mode"),pointMode==="all"?0:pointMode==="selected"?1:2);gl.drawArrays(gl.POINTS,0,flags.length);updateOrbitDebug();drawOverlay()}
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const normalized=a=>{const length=Math.hypot(...a);if(length<1e-12)throw Error("Degenerate crop-frame axis");return a.map(value=>value/length)};
const combine=(coeff,frame)=>[0,1,2].map(i=>coeff[0]*frame.u[i]+coeff[1]*frame.v[i]+coeff[2]*frame.w[i]);
function identityFrame(){return{origin:[0,0,0],u:[1,0,0],v:[0,1,0],w:[0,0,1]}}
function rightHandedFrame(frame){const origin=frame.origin.map(Number),inputU=frame.u.map(Number),inputV=frame.v.map(Number),inputW=frame.w.map(Number),determinant=dot(inputU,cross(inputV,inputW)),valid=Math.abs(Math.hypot(...inputU)-1)<1e-5&&Math.abs(Math.hypot(...inputV)-1)<1e-5&&Math.abs(Math.hypot(...inputW)-1)<1e-5&&Math.abs(dot(inputU,inputV))<1e-5&&Math.abs(dot(inputU,inputW))<1e-5&&Math.abs(dot(inputV,inputW))<1e-5&&determinant>0;if(valid)return{origin,u:inputU,v:inputV,w:inputW};const w=normalized(inputW),projection=dot(inputU,w),u=normalized(inputU.map((value,i)=>value-projection*w[i])),v=normalized(cross(w,u)),repairedU=normalized(cross(v,w));if(dot(repairedU,cross(v,w))<=0)throw Error("Crop frame is not right-handed");return{origin,u:repairedU,v,w}}
function safeWBounds(frame){const values=[];for(const x of meta.bounds.min[0]===meta.bounds.max[0]?[meta.bounds.min[0]]:[meta.bounds.min[0],meta.bounds.max[0]])for(const y of meta.bounds.min[1]===meta.bounds.max[1]?[meta.bounds.min[1]]:[meta.bounds.min[1],meta.bounds.max[1]])for(const z of meta.bounds.min[2]===meta.bounds.max[2]?[meta.bounds.min[2]]:[meta.bounds.min[2],meta.bounds.max[2]])values.push(dot([x-frame.origin[0],y-frame.origin[1],z-frame.origin[2]],frame.w));return[Math.min(...values),Math.max(...values)]}
function setFrame(frame,resetHeights=true,heightBounds=null){cropFrame=rightHandedFrame(frame);localCoordinates=new Float32Array(xyz.length);positions=new Float32Array(xyz.length);const low=[Infinity,Infinity,Infinity],high=[-Infinity,-Infinity,-Infinity],axes=[cropFrame.u,cropFrame.v,cropFrame.w],samples=[[],[],[]],sampleStep=Math.max(1,Math.ceil(xyz.length/3/10000));for(let i=0;i<xyz.length/3;i++){const d=[xyz[i*3]-cropFrame.origin[0],xyz[i*3+1]-cropFrame.origin[1],xyz[i*3+2]-cropFrame.origin[2]];for(let a=0;a<3;a++){const value=dot(d,axes[a]);localCoordinates[i*3+a]=value;low[a]=Math.min(low[a],value);high[a]=Math.max(high[a],value);if(i%sampleStep===0)samples[a].push(value)}}localBounds={min:low,max:high};for(const sample of samples)sample.sort((a,b)=>a-b);const robustLow=samples.map(s=>s[Math.floor((s.length-1)*.005)]),robustHigh=samples.map(s=>s[Math.ceil((s.length-1)*.995)]);localCenter=robustLow.map((value,i)=>(value+robustHigh[i])/2);localHalf=Math.max(...robustHigh.map((value,i)=>value-robustLow[i]))/2||1;for(let i=0;i<positions.length;i++)positions[i]=(localCoordinates[i]-localCenter[i%3])/localHalf;upload(posBuffer,positions);if(resetHeights){const bounds=heightBounds||safeWBounds(cropFrame);configureHeights(bounds[0],bounds[1])}}
function configureHeights(low,high){for(const id of["wmin","wminRange"]){$(id).min=low;$(id).max=high;$(id).value=low;$(id).step=(high-low)/1000||.001}for(const id of["wmax","wmaxRange"]){$(id).min=low;$(id).max=high;$(id).value=high;$(id).step=(high-low)/1000||.001}$("wBounds").textContent=`Local height bounds: ${low.toFixed(4)} … ${high.toFixed(4)}`}
function definition(){return{schema_version:2,crop_frame:cropFrame,polygon_uv:polygon.map(p=>[p[0],p[1]]),w_min:+$("wmin").value,w_max:+$("wmax").value,keep:$("keep").value,boundary_included:$("boundary").checked}}
function pointInside(x,y){return Poly.pointInPolygon(polygon,x,y,$("boundary").checked)}
function updateSelection(){if(!localCoordinates)return;const valid=polygon.length>=3,w0=+$("wmin").value,w1=+$("wmax").value,keep=$("keep").value==="inside";selectedPreview=0;for(let i=0;i<flags.length;i++){const hit=valid&&localCoordinates[i*3+2]>=w0&&localCoordinates[i*3+2]<=w1&&pointInside(localCoordinates[i*3],localCoordinates[i*3+1]);const chosen=keep?hit:!hit;flags[i]=chosen?1:0;if(chosen)selectedPreview++}upload(flagBuffer,flags,gl.DYNAMIC_DRAW);$("selectedCount").textContent=selectedPreview.toLocaleString()+" (preview)";$("percent").textContent=(100*selectedPreview/flags.length).toFixed(2)+"%";$("vertexCount").textContent=polygon.length;$("coords").textContent=JSON.stringify(polygon,null,2);$("uvBounds").textContent=polygon.length?`${Math.min(...polygon.map(p=>p[0])).toFixed(3)}…${Math.max(...polygon.map(p=>p[0])).toFixed(3)} / ${Math.min(...polygon.map(p=>p[1])).toFixed(3)}…${Math.max(...polygon.map(p=>p[1])).toFixed(3)}`:"—";$("wInterval").textContent=`${w0} … ${w1}`;draw()}
function uvToScreen(p){const w=overlay.width,h=overlay.height,f=fitScale();return[w/2+(((p[0]-localCenter[0])/localHalf)*zoom*f[0]+pan[0])*w/2,h/2-(((p[1]-localCenter[1])/localHalf)*zoom*f[1]+pan[1])*h/2]}
function screenToUV(x,y){const w=overlay.clientWidth,h=overlay.clientHeight,f=fitScale();return[localCenter[0]+((x-w/2)/(w/2)-pan[0])/zoom/f[0]*localHalf,localCenter[1]+((h/2-y)/(h/2)-pan[1])/zoom/f[1]*localHalf]}
function nearestVertex(x,y,maxPixels=11){const d=devicePixelRatio;return polygon.reduce((best,p,index)=>{const screen=uvToScreen(p),distance=Math.hypot(screen[0]-x*d,screen[1]-y*d);return distance<best.distance?{index,distance}:best},{index:-1,distance:maxPixels*d}).index}
function screenPolygon(){const d=devicePixelRatio;return polygon.map(point=>{const screen=uvToScreen(point);return[screen[0]/d,screen[1]/d]})}
function edgeInsertionAt(x,y){return Poly.insertAtEdgeHit(polygon,screenPolygon(),[x,y],10)}
function updateEdgeHover(clientX,clientY){if(view!=="top"||polygon.length<2){if(hoverInsert){hoverInsert=null;draw()}return}const rect=canvas.getBoundingClientRect(),x=clientX-rect.left,y=clientY-rect.top;if(nearestVertex(x,y)>=0){if(hoverInsert){hoverInsert=null;draw()}return}const insertion=edgeInsertionAt(x,y);if(!insertion){if(hoverInsert){hoverInsert=null;draw()}return}hoverInsert={edgeIndex:insertion.hit.edgeIndex,point:insertion.point};draw()}
function drawOverlay(){
  ctx.clearRect(0,0,overlay.width,overlay.height);
  if(view==="inspect"){const x=overlay.width/2,y=overlay.height/2,r=7*devicePixelRatio;ctx.strokeStyle="#ff9f43";ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.moveTo(x-r*1.7,y);ctx.lineTo(x+r*1.7,y);ctx.moveTo(x,y-r*1.7);ctx.lineTo(x,y+r*1.7);ctx.stroke();return}
  if(view!=="top"||!polygon.length)return;
  const d=devicePixelRatio;
  ctx.lineWidth=2.5*d;ctx.strokeStyle="#fff176";ctx.fillStyle="#67d5b52e";ctx.beginPath();
  polygon.forEach((p,i)=>{const screen=uvToScreen(p);i?ctx.lineTo(...screen):ctx.moveTo(...screen)});
  if(polygon.length>=3){ctx.closePath();ctx.fill()}
  ctx.stroke();
  if(hoverInsert){const screen=uvToScreen(hoverInsert.point);ctx.beginPath();ctx.arc(screen[0],screen[1],4.5*d,0,Math.PI*2);ctx.fillStyle="#13252b";ctx.fill();ctx.lineWidth=1.75*d;ctx.strokeStyle="#67d5b5";ctx.stroke()}
  for(const p of polygon){const screen=uvToScreen(p);ctx.beginPath();ctx.arc(screen[0],screen[1],7*d,0,Math.PI*2);ctx.fillStyle="#fff176";ctx.fill();ctx.lineWidth=2*d;ctx.strokeStyle="#111";ctx.stroke()}
}
function fitCurrentView(){const orbiting=view==="inspect",target=orbiting?orbitTarget:[0,0,0],result=Nav.fitProjectedBounds(positions,flags,pointMode,target,viewBasis(),canvas.clientWidth,canvas.clientHeight);if(!result){$("message").textContent="No visible preview points to fit.";draw();return}zoom=result.zoom;if(orbiting){pan=[0,0];orbitTarget=result.target;orbitCamera={...orbitCamera,distance:1/zoom}}else pan=result.pan;draw()}
function setView(next){const previous=view,outgoingBasis=viewBasis(),enteringInspect=next==="inspect"&&previous!=="inspect";if(previous==="inspect"&&next!=="inspect")inspectZoom=zoom;if(enteringInspect){if(!inspectCameraInitialized){const state=Nav.inspectStateFromView(outgoingBasis,pan,zoom,fitScale());orbitCamera={tiltX:0,tiltY:0,distance:state.camera.distance};freeOrbitBasis=Nav.topTiltBasis(orbitCamera);orbitTarget=state.target;pan=state.pan;zoom=state.zoom;inspectZoom=zoom;inspectCameraInitialized=true}else{pan=[0,0];zoom=inspectZoom}}view=next;hoverInsert=null;if(next==="top"){$("modeBadge").textContent="TOP / DRAW · rotation locked";$("controlsHint").textContent="Top / Draw: click to add · drag yellow vertex to edit · hover then click/drag edge to insert · right-click vertex to delete"}else if(next==="front"){$("modeBadge").textContent="FRONT · local frame";$("controlsHint").textContent="Front: right/middle drag to pan · wheel to zoom"}else if(next==="side"){$("modeBadge").textContent="SIDE · local frame";$("controlsHint").textContent="Side: right/middle drag to pan · wheel to zoom"}else{$("modeBadge").textContent="3D INSPECT · Top alignment";$("controlsHint").textContent="3D Inspect: left drag tilts from Top · right/middle drag pans · wheel zooms · double click cloud sets pivot"}document.body.classList.toggle("inspect",next==="inspect");document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===next));document.querySelectorAll(".topControl").forEach(b=>b.hidden=next!=="top");if(enteringInspect)draw();else fitCurrentView()}
function useCurrentView(){if(view!=="inspect")return;if(polygon.length&&!confirm("Changing the crop frame makes the existing outline invalid. Clear it and use this view as Top?"))return;polygon=[];const localTop=Nav.topFrameFromView(viewBasis()),old=cropFrame;const next={origin:[...old.origin],u:combine(localTop.u,old),v:combine(localTop.v,old),w:combine(localTop.w,old)};setFrame(next,true);orbitCamera={...orbitCamera,tiltX:0,tiltY:0};freeOrbitBasis=Nav.topTiltBasis(orbitCamera);setView("top");updateSelection();$("message").textContent="Crop frame set from the inspected view; +W points from the scene toward the camera."}
function applyTopOrientation(kind){if(view!=="top")return;const oldMin=+$("wmin").value,oldMax=+$("wmax").value;if(kind==="flip"){cropFrame={origin:[...cropFrame.origin],u:cropFrame.u.map(x=>-x),v:[...cropFrame.v],w:cropFrame.w.map(x=>-x)};polygon=polygon.map(([u,v])=>[-u,v])}else{cropFrame={origin:[...cropFrame.origin],u:cropFrame.u.map(x=>-x),v:cropFrame.v.map(x=>-x),w:[...cropFrame.w]};polygon=polygon.map(([u,v])=>[-u,-v])}setFrame(cropFrame,false);const bounds=safeWBounds(cropFrame);configureHeights(bounds[0],bounds[1]);if(kind==="flip"){$("wmin").value=-oldMax;$("wmax").value=-oldMin}else{$("wmin").value=oldMin;$("wmax").value=oldMax}$("wminRange").value=$("wmin").value;$("wmaxRange").value=$("wmax").value;setView("top");updateSelection();$("message").textContent=kind==="flip"?"Top viewing side flipped; crop volume preserved.":"Top rotated 180° around the height axis; crop volume preserved."}
canvas.addEventListener("mousedown",e=>{dragging=true;last=[e.clientX,e.clientY];dragAction="";hoverInsert=null;if(view==="top"&&e.button===0){const vertex=nearestVertex(e.offsetX,e.offsetY);if(vertex>=0){dragVertex=vertex;dragAction="vertex"}else{const insertion=edgeInsertionAt(e.offsetX,e.offsetY);if(insertion){polygon=insertion.polygon;dragVertex=insertion.dragVertex;dragAction="vertex";updateSelection()}else{polygon=Poly.appendVertex(polygon,screenToUV(e.offsetX,e.offsetY));updateSelection();dragging=false}}}else if(view==="top"&&e.button===2){const vertex=nearestVertex(e.offsetX,e.offsetY);if(vertex>=0){const result=Poly.deleteVertex(polygon,vertex);polygon=result.polygon;dragging=false;if(result.deleted){updateSelection();$("message").textContent="Vertex deleted."}else $("message").textContent="A valid polygon must retain at least three vertices."}else dragAction="pan"}else if(e.button===1||e.button===2){dragAction="pan"}else if(view==="inspect"&&e.button===0){dragAction="orbit"}else dragging=false});
window.addEventListener("mouseup",()=>{if(dragVertex>=0)updateSelection();dragging=false;dragVertex=-1;dragAction="";hoverInsert=null;draw()});
window.addEventListener("mousemove",e=>{if(!dragging){updateEdgeHover(e.clientX,e.clientY);return}const previous=last,dx=e.clientX-previous[0],dy=e.clientY-previous[1];last=[e.clientX,e.clientY];if(dragAction==="vertex"){const r=canvas.getBoundingClientRect();polygon=Poly.moveVertex(polygon,dragVertex,screenToUV(e.clientX-r.left,e.clientY-r.top));updateSelection()}else if(dragAction==="pan"){if(view==="inspect")orbitTarget=Nav.panTarget(orbitTarget,dx,dy,canvas.clientWidth,canvas.clientHeight,zoom,fitScale(),viewBasis());else{pan[0]+=dx/canvas.clientWidth*2;pan[1]-=dy/canvas.clientHeight*2}draw()}else if(dragAction==="orbit"){if(verticalLock){const next=Nav.topTiltDrag({...orbitCamera,target:orbitTarget},dx,dy,canvas.clientWidth,canvas.clientHeight);orbitCamera={tiltX:next.tiltX,tiltY:next.tiltY,distance:next.distance}}else{const next=Nav.freeOrbitDrag({basis:freeOrbitBasis,target:orbitTarget},dx,dy,canvas.clientWidth,canvas.clientHeight);freeOrbitBasis=next.basis}draw()}});
canvas.addEventListener("mouseleave",()=>{if(!dragging&&hoverInsert){hoverInsert=null;draw()}});canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener("wheel",e=>{e.preventDefault();hoverInsert=null;zoom=Math.max(.03,Math.min(100,zoom*Math.exp(-e.deltaY*.001)));if(view==="inspect")orbitCamera={...orbitCamera,distance:1/zoom};draw()},{passive:false});
canvas.addEventListener("dblclick",e=>{if(view!=="inspect")return;const index=Nav.nearestProjectedPoint(positions,flags,pointMode,orbitTarget,viewBasis(),canvas.clientWidth,canvas.clientHeight,zoom,fitScale(),e.offsetX,e.offsetY);if(index<0){$("message").textContent="No preview point close enough to set the pivot.";return}orbitTarget=[positions[index*3],positions[index*3+1],positions[index*3+2]];pan=[0,0];draw();$("message").textContent="Orbit pivot set to the nearest preview point."});
async function loadPreview(){const buffer=await(await fetch("/api/preview")).arrayBuffer(),dv=new DataView(buffer),n=buffer.byteLength/15;xyz=new Float32Array(n*3);colors=new Float32Array(n*3);flags=new Float32Array(n);for(let i=0;i<n;i++){const o=i*15;xyz[i*3]=dv.getFloat32(o,true);xyz[i*3+1]=dv.getFloat32(o+4,true);xyz[i*3+2]=dv.getFloat32(o+8,true);colors[i*3]=dv.getUint8(o+12)/255;colors[i*3+1]=dv.getUint8(o+13)/255;colors[i*3+2]=dv.getUint8(o+14)/255}upload(colorBuffer,colors);upload(flagBuffer,flags,gl.DYNAMIC_DRAW);$("originalCount").textContent=meta.source_point_count.toLocaleString();setFrame(meta.auto_crop_frame||identityFrame(),true,meta.auto_w_bounds||null);setView("top");updateSelection();$("message").textContent=`Auto-level ready: ${meta.auto_level_method||"trimmed PCA"}.`}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("fitView").onclick=fitCurrentView;$("flipTop").onclick=()=>applyTopOrientation("flip");$("rotateTop").onclick=()=>applyTopOrientation("rotate");$("useView").onclick=useCurrentView;
$("verticalLock").checked=verticalLock;
$("verticalLock").onchange=e=>{const currentBasis=view==="inspect"?viewBasis():null;verticalLock=e.target.checked;if(currentBasis){if(verticalLock)orbitCamera=Nav.topTiltFromBasis(currentBasis,orbitCamera.distance,orbitTarget);else freeOrbitBasis=currentBasis;draw()}};
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{pointMode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x===b));draw()});
$("undo").onclick=()=>{hoverInsert=null;polygon.pop();updateSelection()};$("clear").onclick=()=>{hoverInsert=null;polygon=[];updateSelection()};
for(const id of["keep","boundary","wmin","wmax"])$(id).onchange=()=>{if(+$("wmin").value>+$("wmax").value)return;$("wminRange").value=$("wmin").value;$("wmaxRange").value=$("wmax").value;updateSelection()};
for(const pair of[["wminRange","wmin"],["wmaxRange","wmax"]])$(pair[0]).oninput=()=>{$(pair[1]).value=$(pair[0]).value;updateSelection()};
async function post(url,data){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),result=await response.json();if(!response.ok)throw Error(result.error||response.statusText);return result}
async function refreshExportInventory(){const response=await fetch("/api/exports"),inventory=await response.json();$("legacyExport").textContent=inventory.legacy_export?"Existing root export files preserved.":"";return inventory}
async function beginExport(action){try{await post("/api/export",{action,definition:definition()});$("report").textContent="";poll()}catch(e){alert(e.message)}}
$("save").onclick=async()=>{try{await post("/api/definition",definition());$("message").textContent="Crop definition and local frame saved."}catch(e){alert(e.message)}};
$("load").onclick=async()=>{const response=await fetch("/api/definition");if(!response.ok)return alert("No saved crop definition exists.");applyDefinition((await response.json()).definition)};
$("export").onclick=async()=>{if(polygon.length<3)return alert("Draw at least three outline vertices first.");try{const destination=await post("/api/export-destination",{});if(!destination.selected)return;const inventory=await refreshExportInventory();if(!inventory.versions.length){await beginExport("new");return}$("exportDialogMessage").textContent=`Latest version: ${inventory.latest.version}. Create a new immutable version or explicitly replace that latest version.`;$("exportDialog").showModal()}catch(e){alert(e.message)}};
$("exportNew").onclick=()=>{$("exportDialog").close();beginExport("new")};
$("exportReplace").onclick=()=>{const latest=$("exportDialogMessage").textContent.match(/crop_\d+/)?.[0]||"latest export";$("exportDialog").close();if(confirm(`Replace ${latest}? The previous version is kept unless the replacement finishes successfully.`))beginExport("replace_latest")};
$("exportCancel").onclick=()=>$("exportDialog").close();
function applyDefinition(d){if(d.schema_version===1){setFrame(identityFrame(),false);polygon=d.polygon;const bounds=safeWBounds(cropFrame);configureHeights(bounds[0],bounds[1]);$("wmin").value=d.z_min;$("wmax").value=d.z_max}else{setFrame(d.crop_frame,false);polygon=d.polygon_uv;const bounds=safeWBounds(cropFrame);configureHeights(Math.min(bounds[0],d.w_min),Math.max(bounds[1],d.w_max));$("wmin").value=d.w_min;$("wmax").value=d.w_max}$("wminRange").value=$("wmin").value;$("wmaxRange").value=$("wmax").value;$("keep").value=d.keep;$("boundary").checked=d.boundary_included!==false;setView("top");updateSelection()}
async function poll(){try{const s=await(await fetch("/api/status")).json();$("status").textContent=s.phase;$("progress").value=s.progress||0;if(s.message)$("message").textContent=s.message;if(s.metadata&&!meta){meta=s.metadata;await loadPreview();await refreshExportInventory()}if(s.report){$("report").textContent=`Export complete\nVersion: ${s.report.export_version}\nExact points: ${s.report.output_point_count.toLocaleString()}\nRaw: ${s.report.raw_output_ply}\nAligned: ${s.report.aligned_output_ply}`;await refreshExportInventory()}if(["preparing","exporting"].includes(s.phase))setTimeout(poll,500);else if(s.phase==="error")$("message").textContent="Error: "+s.message}catch(e){$("status").textContent="Disconnected";setTimeout(poll,1000)}}
initGL();addEventListener("resize",resize);resize();poll();
