(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;else root.CropPolygon=api})(typeof window!=="undefined"?window:globalThis,function(){
  "use strict";
  function appendVertex(polygon,point){return[...polygon,[point[0],point[1]]]}
  function insertVertex(polygon,edgeIndex,point){if(edgeIndex<0||edgeIndex>=polygon.length)throw Error("Polygon edge index is out of range");const result=polygon.map(vertex=>[...vertex]);result.splice(edgeIndex+1,0,[point[0],point[1]]);return result}
  function moveVertex(polygon,index,point){if(index<0||index>=polygon.length)throw Error("Polygon vertex index is out of range");const result=polygon.map(vertex=>[...vertex]);result[index]=[point[0],point[1]];return result}
  function deleteVertex(polygon,index){if(index<0||index>=polygon.length)return{polygon:polygon.map(vertex=>[...vertex]),deleted:false};if(polygon.length===3)return{polygon:polygon.map(vertex=>[...vertex]),deleted:false};const result=polygon.map(vertex=>[...vertex]);result.splice(index,1);return{polygon:result,deleted:true}}
  function nearestPointOnSegment(point,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],lengthSquared=dx*dx+dy*dy,t=lengthSquared?Math.max(0,Math.min(1,((point[0]-a[0])*dx+(point[1]-a[1])*dy)/lengthSquared)):0,nearest=[a[0]+t*dx,a[1]+t*dy];return{point:nearest,t,distance:Math.hypot(point[0]-nearest[0],point[1]-nearest[1])}}
  function nearestEdgeHit(screenPolygon,cursor,threshold=10){if(screenPolygon.length<2)return null;const edgeCount=screenPolygon.length>=3?screenPolygon.length:screenPolygon.length-1;let best=null;for(let edgeIndex=0;edgeIndex<edgeCount;edgeIndex++){const nextIndex=(edgeIndex+1)%screenPolygon.length,nearest=nearestPointOnSegment(cursor,screenPolygon[edgeIndex],screenPolygon[nextIndex]);if(nearest.distance<=threshold&&(!best||nearest.distance<best.distance))best={edgeIndex,insertIndex:edgeIndex+1,nextIndex,point:nearest.point,t:nearest.t,distance:nearest.distance}}return best}
  function insertAtEdgeHit(polygon,screenPolygon,cursor,threshold=10){const hit=nearestEdgeHit(screenPolygon,cursor,threshold);if(!hit)return null;const a=polygon[hit.edgeIndex],b=polygon[hit.nextIndex],point=[a[0]+hit.t*(b[0]-a[0]),a[1]+hit.t*(b[1]-a[1])];return{polygon:insertVertex(polygon,hit.edgeIndex,point),dragVertex:hit.insertIndex,point,hit}}
  function pointInPolygon(polygon,x,y,boundaryIncluded=true){if(polygon.length<3)return false;let inside=false,on=false;const tolerance=1e-9;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j],cross=(x-a[0])*(b[1]-a[1])-(y-a[1])*(b[0]-a[0]);if(Math.abs(cross)<tolerance&&x>=Math.min(a[0],b[0])-tolerance&&x<=Math.max(a[0],b[0])+tolerance&&y>=Math.min(a[1],b[1])-tolerance&&y<=Math.max(a[1],b[1])+tolerance)on=true;if(((a[1]>y)!=(b[1]>y))&&(x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]))inside=!inside}return boundaryIncluded?(inside||on):(inside&&!on)}
  return{appendVertex,insertVertex,moveVertex,deleteVertex,nearestPointOnSegment,nearestEdgeHit,insertAtEdgeHit,pointInPolygon};
});
